import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

type LanguageCode = 'ja' | 'ko' | 'en';

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (language: LanguageCode) => Promise<void>;
  t: (key: string) => string; // Translation function
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translations - in a real app, this would be loaded from files
const translations: Record<LanguageCode, Record<string, string>> = {
  ja: {
    'settings.title': '設定',
    'settings.theme': 'テーマ',
    'settings.theme_light': 'ライト',
    'settings.theme_dark': 'ダーク',
    'settings.theme_system': 'システム',
    'settings.language': '言語',
    'settings.notifications': '通知',
    'settings.privacy': 'プライバシー',
    'settings.push_notifications': 'プッシュ通知',
    'settings.email_notifications': 'メール通知',
    'settings.profile_visibility': 'プロフィール表示',
    'settings.show_online_status': 'オンライン状態を表示',
    'settings.public': '公開',
    'settings.private': '非公開',
    'settings.back': '戻る',
    'settings.language_updated': '言語が更新されました',
    'settings.language_update_failed': '言語の更新に失敗しました',
    'profile.title': 'プロフィール',
    'profile.display_name': '表示名',
    'profile.display_name_placeholder': '表示名を入力してください',
    'profile.display_name_required': '表示名は必須です',
    'profile.email': 'メールアドレス',
    'profile.email_placeholder': 'メールアドレスを入力してください',
    'profile.email_required': 'メールアドレスは必須です',
    'profile.email_invalid': '有効なメールアドレスを入力してください',
    'profile.bio': '自己紹介',
    'profile.bio_placeholder': '自己紹介を入力してください',
    'profile.cancel': 'キャンセル',
    'profile.saving': '保存中...',
    'profile.save': '保存',
    'profile.discard': '破棄',
    'profile.discard_changes_title': '変更を破棄しますか？',
    'profile.discard_changes_message': '変更を破棄してもよろしいですか？',
    'profile.update_success': 'プロフィールが正常に更新されました',
    'profile.update_failed': 'プロフィールの更新に失敗しました',
    'home.no_conversations': '会話がありません',
    'home.new_conversation': '新しい会話を開始',
    'home.hello': 'こんにちは',
    'home.logout': 'ログアウト',
    'home.logging_out': 'ログアウト中...',
    'auth.welcome': 'AidenGPTへようこそ',
    'auth.welcome_back': 'おかえりなさい',
    'auth.reset_password': 'パスワードリセット',
    'auth.forgot_password': 'パスワードを忘れた場合',
    'auth.back_to_signin': 'サインインに戻る',
    'auth.no_account_signup': 'アカウントをお持ちでない場合は登録',
    'auth.have_account_signin': 'すでにアカウントをお持ちの場合はサインイン',
    'chat.model': 'モデル：',
    'chat.type_message': 'メッセージを入力...',
    'chat.send': '送信',
    'chat.sending': '...',
    'error.screen_not_found': 'この画面は存在しません。',
    'error.go_home': 'ホーム画面に移動！',
    'auth.login_with_google': 'Googleでログイン',
    'auth.redirecting': 'リダイレクト中...',
    'auth.sign_in_with_email': 'メールでログイン',
    'auth.retry_connection': '接続を再試行',
    'auth.signing_in': 'サインイン中...',
    'auth.creating_account': 'アカウント作成中...',
    'auth.sign_up': '登録',
    'auth.sign_in': 'サインイン',
    'auth.sending': '送信中...',
    'auth.send_reset_link': 'リセットリンクを送信',
    'auth.email_placeholder': 'メールアドレス',
    'auth.password_placeholder': 'パスワード',
    'auth.confirm_password_placeholder': 'パスワード確認',
    'auth.email_required': 'メールアドレスは必須です',
    'auth.valid_email_required': '有効なメールアドレスを入力してください',
    'auth.password_required': 'パスワードは必須です',
    'auth.password_min_length': 'パスワードは8文字以上である必要があります',
    'auth.confirm_password_required': 'パスワード確認は必須です',
    'auth.passwords_dont_match': 'パスワードが一致しません',
    'auth.please_enter_email': 'メールアドレスを入力してください',
    'auth.please_enter_valid_email': '有効なメールアドレスを入力してください',
    'auth.success': '成功',
    'auth.account_created_success': 'アカウントが正常に作成されました！',
    'auth.check_email_confirm': 'メールを確認して、アカウントを有効化するための確認リンクをクリックしてください。その後、サインインできます。',
    'auth.signup_failed': '登録に失敗しました',
    'auth.failed_create_account': 'アカウントの作成に失敗しました。もう一度お試しください。',
    'auth.signin_failed': 'サインインに失敗しました',
    'auth.failed_signin': 'サインインに失敗しました。認証情報を確認して、もう一度お試しください。',
    'auth.welcome_back_toast': 'おかえりなさい！',
    'auth.signed_in_successfully': '正常にログインしました。',
    'auth.unexpected_error': '予期しないエラーが発生しました。もう一度お試しください。',
    'auth.password_reset_sent': 'パスワードリセットメールを送信しました。メールを確認して指示に従ってください。',
    'auth.forgot_password_description': 'メールアドレスを入力すると、パスワードをリセットするためのリンクをお送りします。',
    'auth.create_account': 'アカウント作成',
    'auth.or': 'または',
    'auth.test_navigation': 'テストナビゲーション',
    'settings.loading': '設定を読み込み中...',
    'settings.error': 'エラー',
    'explore.title': '探索画面',
    'explore.coming_soon': '近日公開...',
  },
  ko: {
    'settings.title': '설정',
    'settings.theme': '테마',
    'settings.theme_light': '라이트',
    'settings.theme_dark': '다크',
    'settings.theme_system': '시스템',
    'settings.language': '언어',
    'settings.notifications': '알림',
    'settings.privacy': '개인정보',
    'settings.push_notifications': '푸시 알림',
    'settings.email_notifications': '이메일 알림',
    'settings.profile_visibility': '프로필 표시',
    'settings.show_online_status': '온라인 상태 표시',
    'settings.public': '공개',
    'settings.private': '비공개',
    'settings.back': '뒤로',
    'settings.language_updated': '언어가 업데이트되었습니다',
    'settings.language_update_failed': '언어 업데이트에 실패했습니다',
    'profile.title': '프로필',
    'profile.display_name': '표시 이름',
    'profile.display_name_placeholder': '표시 이름을 입력하세요',
    'profile.display_name_required': '표시 이름은 필수입니다',
    'profile.email': '이메일',
    'profile.email_placeholder': '이메일을 입력하세요',
    'profile.email_required': '이메일은 필수입니다',
    'profile.email_invalid': '유효한 이메일을 입력하세요',
    'profile.bio': '자기소개',
    'profile.bio_placeholder': '자기소개를 입력하세요',
    'profile.cancel': '취소',
    'profile.saving': '저장 중...',
    'profile.save': '저장',
    'profile.discard': '삭제',
    'profile.discard_changes_title': '변경사항을 삭제하시겠습니까?',
    'profile.discard_changes_message': '변경사항을 삭제하시겠습니까?',
    'profile.update_success': '프로필이 성공적으로 업데이트되었습니다',
    'profile.update_failed': '프로필 업데이트에 실패했습니다',
    'home.no_conversations': '대화가 없습니다',
    'home.new_conversation': '새 대화 시작',
    'home.hello': '안녕하세요',
    'home.logout': '로그아웃',
    'home.logging_out': '로그아웃 중...',
    'auth.welcome': 'AidenGPT에 오신 것을 환영합니다',
    'auth.welcome_back': '다시 오신 것을 환영합니다',
    'auth.reset_password': '비밀번호 재설정',
    'auth.forgot_password': '비밀번호를 잊으셨나요',
    'auth.back_to_signin': '로그인으로 돌아가기',
    'auth.no_account_signup': '계정이 없으신가요? 가입하기',
    'auth.have_account_signin': '이미 계정이 있으신가요? 로그인',
    'chat.model': '모델:',
    'chat.type_message': '메시지를 입력하세요...',
    'chat.send': '보내기',
    'chat.sending': '...',
    'error.screen_not_found': '이 화면은 존재하지 않습니다.',
    'error.go_home': '홈 화면으로 이동!',
    'auth.login_with_google': 'Google로 로그인',
    'auth.redirecting': '리디렉션 중...',
    'auth.sign_in_with_email': '이메일로 로그인',
    'auth.retry_connection': '연결 재시도',
    'auth.signing_in': '로그인 중...',
    'auth.creating_account': '계정 생성 중...',
    'auth.sign_up': '가입',
    'auth.sign_in': '로그인',
    'auth.sending': '전송 중...',
    'auth.send_reset_link': '재설정 링크 보내기',
    'auth.email_placeholder': '이메일',
    'auth.password_placeholder': '비밀번호',
    'auth.confirm_password_placeholder': '비밀번호 확인',
    'auth.email_required': '이메일은 필수입니다',
    'auth.valid_email_required': '유효한 이메일을 입력하세요',
    'auth.password_required': '비밀번호는 필수입니다',
    'auth.password_min_length': '비밀번호는 최소 8자 이상이어야 합니다',
    'auth.confirm_password_required': '비밀번호 확인은 필수입니다',
    'auth.passwords_dont_match': '비밀번호가 일치하지 않습니다',
    'auth.please_enter_email': '이메일 주소를 입력해주세요',
    'auth.please_enter_valid_email': '유효한 이메일 주소를 입력해주세요',
    'auth.success': '성공',
    'auth.account_created_success': '계정이 성공적으로 생성되었습니다!',
    'auth.check_email_confirm': '이메일을 확인하고 계정을 활성화하기 위한 확인 링크를 클릭하세요. 그 후 로그인할 수 있습니다.',
    'auth.signup_failed': '가입에 실패했습니다',
    'auth.failed_create_account': '계정 생성에 실패했습니다. 다시 시도해주세요.',
    'auth.signin_failed': '로그인에 실패했습니다',
    'auth.failed_signin': '로그인에 실패했습니다. 자격 증명을 확인하고 다시 시도해주세요.',
    'auth.welcome_back_toast': '다시 오신 것을 환영합니다!',
    'auth.signed_in_successfully': '성공적으로 로그인되었습니다.',
    'auth.unexpected_error': '예상치 못한 오류가 발생했습니다. 다시 시도해주세요.',
    'auth.password_reset_sent': '비밀번호 재설정 이메일을 보냈습니다. 이메일을 확인하고 지시를 따르세요.',
    'auth.forgot_password_description': '이메일 주소를 입력하면 비밀번호를 재설정할 수 있는 링크를 보내드립니다.',
    'auth.create_account': '계정 만들기',
    'auth.or': '또는',
    'auth.test_navigation': '테스트 네비게이션',
    'settings.loading': '설정을 불러오는 중...',
    'settings.error': '오류',
    'explore.title': '탐색 화면',
    'explore.coming_soon': '곧 출시 예정...',
  },
  en: {
    'settings.title': 'Settings',
    'settings.theme': 'Theme',
    'settings.theme_light': 'Light',
    'settings.theme_dark': 'Dark',
    'settings.theme_system': 'System',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.push_notifications': 'Push Notifications',
    'settings.email_notifications': 'Email Notifications',
    'settings.profile_visibility': 'Profile Visibility',
    'settings.show_online_status': 'Show Online Status',
    'settings.public': 'Public',
    'settings.private': 'Private',
    'settings.back': 'Back',
    'settings.language_updated': 'Language updated successfully',
    'settings.language_update_failed': 'Failed to update language',
    'profile.title': 'Profile',
    'profile.display_name': 'Display Name',
    'profile.display_name_placeholder': 'Enter your display name',
    'profile.display_name_required': 'Display name is required',
    'profile.email': 'Email',
    'profile.email_placeholder': 'Enter your email',
    'profile.email_required': 'Email is required',
    'profile.email_invalid': 'Please enter a valid email',
    'profile.bio': 'Bio',
    'profile.bio_placeholder': 'Enter your bio',
    'profile.cancel': 'Cancel',
    'profile.saving': 'Saving...',
    'profile.save': 'Save',
    'profile.discard': 'Discard',
    'profile.discard_changes_title': 'Discard Changes?',
    'profile.discard_changes_message': 'Are you sure you want to discard your changes?',
    'profile.update_success': 'Profile updated successfully',
    'profile.update_failed': 'Failed to update profile',
    'home.no_conversations': 'No conversations',
    'home.new_conversation': 'Start new conversation',
    'home.hello': 'Hello',
    'home.logout': 'Logout',
    'home.logging_out': 'Logging out...',
    'auth.welcome': 'Welcome to AidenGPT',
    'auth.welcome_back': 'Welcome Back',
    'auth.reset_password': 'Reset Password',
    'auth.forgot_password': 'Forgot Password',
    'auth.back_to_signin': 'Back to Sign In',
    'auth.no_account_signup': "Don't have an account? Sign Up",
    'auth.have_account_signin': 'Already have an account? Sign In',
    'chat.model': 'Model:',
    'chat.type_message': 'Type a message...',
    'chat.send': 'Send',
    'chat.sending': '...',
    'error.screen_not_found': 'This screen does not exist.',
    'error.go_home': 'Go to home screen!',
    'auth.login_with_google': 'Login with Google',
    'auth.redirecting': 'Redirecting...',
    'auth.sign_in_with_email': 'Sign In with Email',
    'auth.retry_connection': 'Retry Connection',
    'auth.signing_in': 'Signing In...',
    'auth.creating_account': 'Creating Account...',
    'auth.sign_up': 'Sign Up',
    'auth.sign_in': 'Sign In',
    'auth.sending': 'Sending...',
    'auth.send_reset_link': 'Send Reset Link',
    'auth.email_placeholder': 'Email',
    'auth.password_placeholder': 'Password',
    'auth.confirm_password_placeholder': 'Confirm Password',
    'auth.email_required': 'Email is required',
    'auth.valid_email_required': 'Please enter a valid email address',
    'auth.password_required': 'Password is required',
    'auth.password_min_length': 'Password must be at least 8 characters long',
    'auth.confirm_password_required': 'Please confirm your password',
    'auth.passwords_dont_match': 'Passwords do not match',
    'auth.please_enter_email': 'Please enter your email address',
    'auth.please_enter_valid_email': 'Please enter a valid email address',
    'auth.success': 'Success',
    'auth.account_created_success': 'Account Created Successfully!',
    'auth.check_email_confirm': 'Please check your email and click the confirmation link to activate your account. You can then sign in.',
    'auth.signup_failed': 'Signup Failed',
    'auth.failed_create_account': 'Failed to create account. Please try again.',
    'auth.signin_failed': 'Sign In Failed',
    'auth.failed_signin': 'Failed to sign in. Please check your credentials and try again.',
    'auth.welcome_back_toast': 'Welcome back!',
    'auth.signed_in_successfully': 'You have been signed in successfully.',
    'auth.unexpected_error': 'An unexpected error occurred. Please try again.',
    'auth.password_reset_sent': 'Password reset email sent. Please check your email and follow the instructions.',
    'auth.forgot_password_description': 'Enter your email address and we\'ll send you a link to reset your password.',
    'auth.create_account': 'Create Account',
    'auth.or': 'or',
    'auth.test_navigation': 'Test Navigation',
    'settings.loading': 'Loading settings...',
    'settings.error': 'Error',
    'explore.title': 'Explore Screen',
    'explore.coming_soon': 'Coming soon...',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguageState] = useState<LanguageCode>('en');

  // Load saved language from storage
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem('user-language');
        if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
          setCurrentLanguageState(savedLanguage as LanguageCode);
        }
      } catch (error) {
        console.error('Failed to load language:', error);
      }
    };

    loadLanguage();
  }, []);

  const setLanguage = async (language: LanguageCode) => {
    try {
      await AsyncStorage.setItem('user-language', language);
      setCurrentLanguageState(language);
    } catch (error) {
      console.error('Failed to save language:', error);
    }
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key] || key;
  };

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      setLanguage,
      t,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguageContext() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguageContext must be used within a LanguageProvider');
  }
  return context;
} 